// Enums as objects
export const Role = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  VIEWER: 'VIEWER',
};

export const Page = {
  HOME: 'HOME',
  ANNOUNCEMENTS: 'ANNOUNCEMENTS',
  ACHIEVEMENTS: 'ACHIEVEMENTS',
  EVENTS: 'EVENTS',
  ADMIN: 'ADMIN',
  PROFILE: 'PROFILE',
  DONATIONS: 'DONATIONS',
  CHAT: 'CHAT',
  AI_STUDIO: 'AI_STUDIO',
  HELP: 'HELP',
  ADMIN_CONTENT: 'ADMIN_CONTENT',
};
